
# -*- coding: utf-8 -*-
"""lora_write_v3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VyJlLqjfR6qSQSaQtFqURSnwIyQy2rci
"""

import time
time.sleep(5)
import os
import serial
import sys
import RPi.GPIO as GPIO
import re

import socket
ClientSocket = socket.socket()
host = '192.168.1.30'
port = 1233

print('Waiting for connection')
try:
    ClientSocket.connect((host, port))
except socket.error as e:
    print(str(e))

Response = ClientSocket.recv(1024)


COM_PORT = '/dev/ttyACM1' #指定通訊埠名稱
BAUD_RATES = 9600  # 設定傳輸速率
ser = serial.Serial(COM_PORT, BAUD_RATES)  # 初始化序列通訊埠


x = 0
y = 0
valB = 0
xold=128
yold=128
mode_old = 0

while True:
    start=time.time()
    data_raw = ser.readline()  # 讀取一行
    
    
    try:
      data = data_raw.decode()  # 用預設的UTF-8解碼
    except:
      data = "128"
      pass
#     f= open('Beta_FBMode.txt','r+')
#     FBmodetype=f.readline()
#     f.close()
#    # print(FBmodetype)
#     f= open('Beta_LRMode.txt','r+')
#     LRmodetype=f.readline()
#     f.close()
    #print(LRmodetype)
    print(data)
    
    #---------LoRa switch mode-------------------
    if data[0:4] == "LoRa":
        print("LoRa")
        mode_new = 1 
        if mode_new != mode_old:
            Input = 'LRM=1o'
            ClientSocket.send(str.encode(Input))
            mode_old=mode_new
    elif data[0:3] == "ASM":
        print("ASM")
        mode_new = 2 
        if mode_new != mode_old:
            Input = 'LRM=2o'
            ClientSocket.send(str.encode(Input))
            mode_old=mode_new
    elif data[0:5]== "mode3":
        print("always-left")
        mode_new = 3 
        if mode_new != mode_old:
            Input = 'LRM=3o'
            ClientSocket.send(str.encode(Input))
            mode_old=mode_new
#----------TURN ON THE CHASSIS---------------'''    
    if data[1:5] == "valB":
        Input = 'chassis'
        ClientSocket.send(str.encode(Input))

#-------------WRITE THE X VALUE--------------    
    #if FBmodetype=="1": #單訊號控制
    elif data[1] == "X":
      ##處理字串
      x = data[1::]            
      x = ''.join([x for x in data if x.isdigit()]) #找尋數字            
      #print('x=',x)
      if x != xold:
        with open('FBmotor_lora.txt','w') as motorfile:
          # ~ motorfile.seek(0)
          motorfile.write("X=%s" %(x))
          motorfile.flush
          # ~ motorfile.close()

#-------------WRITE THE Y VALUE--------------                 
    #if LRmodetype=="0,1,0":
    elif data[1] == "Y":
      ##處理字串
      y = data[1::]            
      y = ''.join([y for y in data if y.isdigit()]) #找尋數字            
      #print('y=',y)
      if y != yold:
        Input='LRY='+str(y)+'o'
        ClientSocket.send(str.encode(Input))
              
    end=time.time()
    FPS=round(1/(end-start),2)
    print('FPS:',FPS)
    xold=x
    yold=y
              
    print("--------------------------")
          # ~ elif data[1:5] == "valB": #單訊號控制
              # ~ valB = data[1:5:]
              # ~ print(valB)
              # ~ tripodfile = open('Beta_TransferTripodData.txt','w+')
              # ~ tripodfile.seek(0)
              # ~ tripodfile.write("%s" %(valB))
              

              
              
          # ~ motorfile = open('Beta_TransferFBMotorData.txt','w+')
          # ~ motorfile.seek(0)
          # ~ motorfile.write("X=%s,Y=%s" %(x,y))
